name = "Ribbit Survival"
author = "Flatts3000"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "65363bf7350b2f17e4cacf430cc8587fe4aedb348c63c5c1376a58d686f175f5"

[versions]
minecraft = "26.1.2"
neoforge = "26.1.2.76"
