name = "Ribbit Survival"
author = "Flatts3000"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b83c2a2fb3817cec3d6d0dbba1ee87f2692fef6d6d75e96d5ffd1548e1c717ef"

[versions]
minecraft = "26.1.2"
neoforge = "26.1.2.76"
